;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================



[colors]

background     = #18233A
background-alt = #22304A

foreground     = #EDF4FF

primary        = #7FA8C9
secondary      = #95B8D1

disabled       = #6D7894
alert          = #D97A7A


[bar/bar1]
override-redirect = true

width = 99%
height = 23pt
offset-x = .5%
offset-y = 4
radius = 8
; dpi = 96


background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0pt

border-size = 0pt
border-color = #00000000

module-margin = 0
font-0 = UbuntuMono Nerd Font:style=Regular:size=13;2
;font-0 = UbuntuMono Nerd Font:style=Bold:size=13;2
font-1 = JetBrainsMono Nerd Font:size=11;1

;font-0 = UbuntuMono Nerd Font:style=Bold:size=13;2
;font-1 = JetBrainsMono Nerd Font:size=11;1

modules-left = logo target_to_hack ip-htb 
modules-center = xworkspaces
modules-right = ip-only pulseaudio time brightness bluetooth powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html


[bar/bar2]
override-redirect = true

width = 99%
height = 20pt
offset-x = .5%
offset-y = 6
radius = 6
; dpi = 96

bottom = true


background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0pt

border-size = 0pt
border-color = #00000000


module-margin = 0


font-0 = UbuntuMono Nerd Font:style=Regular:size=11;2

modules-left = filesystem filesystem2 memory cpu temperature 
modules-center = xwindow
modules-right = wireless-speed date charge logop ;systray 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/logo]
type = custom/text
content = "   ¦ i3 "  
; 󰂧          󰆍     󰘧  󰌾   󰍁 󰌽 󰣖 
format-background = #2d206b
format-padding = 2
format-underline = #6f49f5

[module/logop] 
type = custom/text 
content = " 󰍁  ? Murdox~  "
;          󰆍     󰘧  󰌾   󰍁 󰌽 󰣖 
format-background = #2d206b
format-padding = 1
format-underline = #6f49f5

[module/brightness]
type = custom/script
;exec = brightnessctl get | awk '{printf "󰃞  %d%%"}'
exec = /home/mrdx/.config/polybar/get_brightness.sh
interval = 1
format=<label>
format-underline=#67C8FF
format-foreground = #FFD166 
label-foreground = #FFD168
format-background = ${colors.background}
format-padding=1

[module/systray]
type = internal/tray

tray-size = 11pt
format-padding=2
format-background=${colors.background}
format-underline = #1c1c1c


[module/wireless-speed]
type = internal/network
interface = wlo1

label-connected =  %upspeed:7%   %downspeed:7%
format-connected = %{A1:nm-connection-editor:}%{F#67C8FF}%{F-}  <label-connected>%{A}

format-connected-padding = 1

format-connected-background = ${colors.background}
format-connected-foreground = ${colors.foreground}
format-connected-underline = #03fcbe

[module/ip-only]
type = internal/network
interface = wlo1


label-connected = %local_ip%
format-connected = %{T2}%{F#03fcbe}󰈀%{F-}%{T-}  <label-connected>
format-connected-padding = 1

format-connected-background = ${colors.background}
format-connected-foreground = ${colors.foreground}


[module/ip-htb]
type = internal/network
interface = tun0
interval = 2

label-connected = %local_ip%
format-connected = %{T2}%{F#03fcbe}󰆧%{F-}%{T-} <label-connected>
format-connected-padding = 1

format-connected-background = ${colors.background}
format-connected-foreground = ${colors.foreground}

label-disconnected = "Disconnected"
format-disconnected = %{T2}%{F#03fcbe}󰆧%{F-}%{T-} <label-disconnected>
format-disconnected-padding = 1
format-disconnected-background = ${colors.background}
format-disconnected-foreground = ${colors.foreground}


;[module/wireless-network]
;type = internal/network
;click-left = sh -c "/usr/bin/nm-connection-editor"
;interface = wlo1
;label-connected = %local_ip%  %upspeed:9% %downspeed:9%
;label-upspeed = %upspeed:9%
;label-downspeed = %downspeed:9%
;format-connected = %{A1:nm-connection-editor:}  <label-connected>%{A}
;format-connected-padding=2
;format-connected-background=${colors.background}
;format-connected-foreground=#03fcbe
;format-connected-underline=#03fcbe
;label-connected-foreground=${colors.foreground}

[module/test-click]
type = custom/text
content = "Prueba Click"
click-left = sh -c "notify-send 'Click izquierdo detectado'"
click-right = sh -c "notify-send 'Click derecho detectado'"



[module/xworkspaces]
type = internal/xworkspaces

; 🔑 MOSTRAR TODOS SIEMPRE
show-empty = true
pin-workspaces = true
enable-click = true
enable-scroll = false

; deben coincidir con i3 (los tuyos son numéricos, está bien)
workspace-names = 1;2;3;4;5;6;7;8;9

; ACTIVO → medio lleno
label-active = %{T2}◉%{T-}
label-active-foreground = #ffffff
;${colors.primary}
label-active-padding = 1

; OCUPADO → lleno
label-occupied = %{T2}●%{T-}
label-occupied-foreground = #ffffff 
;${colors.foreground}
label-occupied-padding = 1

; VACÍO → círculo
label-empty = %{T2}○%{T-}
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

; URGENTE
label-urgent = %{T2}●%{T-}
label-urgent-foreground = ${colors.alert}
label-urgent-padding = 1


;[module/xworkspaces]
;type = internal/xworkspaces

;label-active = %name%
;label-active-background = ${colors.background-alt}
;label-active-underline= ${colors.primary}
;label-active-padding = 2

;label-occupied = %name%
;label-occupied-padding = 2

;label-urgent = %name%
;label-urgent-background = ${colors.alert}
;label-urgent-padding = 1

;label-empty = %name%
;label-empty-foreground = ${colors.disabled}
;label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %percentage_used%%
format-mounted = "  <label-mounted>"
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}
format-mounted-padding=2
format-mounted-underline=#c90047
format-mounted-foreground=#67C8FF
label-mounted-foreground=${colors.foreground}
format-mounted-background=${colors.background}

[module/filesystem2]
type = internal/fs
interval = 25

mount-0 = /home

label-mounted = %percentage_used%%
format-mounted = "  <label-mounted>"
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}
format-mounted-padding = 1
format-mounted-underline = #ff8800
format-mounted-foreground = #8ACBFF
label-mounted-foreground = ${colors.foreground}
format-mounted-background = ${colors.background}


[module/temperature]
type = internal/temperature
warn-temperature=100
; Seconds to sleep between updates
; Default: 1
interval = 0.5
label = %temperature-c%
format= "  <label>"
format-foreground=#FFB86C
label-foreground=${colors.foreground}
format-underline=#cf1717
format-padding=1
format-background=${colors.background}

[module/pulseaudio]
type = internal/pulseaudio

;format-volume-prefix = "  "
;format-volume-prefix-foreground = ${colors.foreground}
format-volume = <ramp-volume>  <label-volume>

format-volume-background=${colors.background}
;#2d206b
format-volume-padding=1

label-volume = %percentage%%
format-volume-underline =#04c75c 
ramp-volume-2 = 
ramp-volume-1 = 
ramp-volume-0 = 

format-volume-foreground=#67C8FF
label-volume-foreground = ${colors.foreground}
label-muted = "  muted"
format-muted-underline =${colors.disabled}
label-muted-foreground = ${colors.disabled}
format-muted-padding=2
format-muted-background=#2d206b

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
label = %percentage_used:2%%
format-background=${colors.background}
format-padding=1
format-prefix-foreground=#8ACBFF
format-underline=#00bd00

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground =#008fd1 
label = %percentage:2%%
format-underline=#008fd1
format-padding=1
format-background=${colors.background}


	
[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = custom/script
exec = ~/.config/polybar/date.sh
interval = 60
label-foreground = ${colors.foreground}
format-foreground=#4FA3FF
format-padding = 1
format-background=${colors.background}

[module/time]

type = custom/script
exec = ~/.config/polybar/time.sh
interval = 30
label-foreground = ${colors.foreground}
format-foreground=#4FA3FF
format-padding = 1
format-background=${colors.background}

[module/charge]

type = custom/script
exec = ~/.config/polybar/charge.sh
interval = 60
label-foreground = ${colors.foreground}
format-foreground=#4FA3FF
format-padding = 1
format-background=${colors.background}




[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini



[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
interval = 3

click-left = blueman-manager

format = <label>
format-padding = 1
format-background = ${colors.background}
format-foreground = ${colors.foreground}

label = %{T2}%{F#03fcbe}%{F-}
label-on = %{T2}%{F#03fcbe}%{F-}
label-off = %{T2}%{F#555555}%{F-}

[module/powermenu]
type = custom/text
content = %{T2}%{F#ff3b3b}⏻%{F-}%{T-}

click-left = ~/.config/polybar/scripts/powermenu.sh

content-padding = 2
content-background = ${colors.background}


;settarget

[module/target_to_hack]
type = custom/script
interval = 2
exec = ~/.config/bin/target_to_hack.sh

;format = <label>

format-padding = 1
;format-background = ${colors.background}
;format-foreground = ${colors.foreground}
